name: imbalance-multi-classification
channels:
  - pytorch
  - plotly
  - nvidia
  - intel
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - altair=4.2.2
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=11.0.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.6.2
  - boost-cpp=1.78.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - cachetools=5.3.0
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.3
  - colorama=0.4.6
  - comm=0.1.2
  - console_shortcut=0.1.1
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cuda-cccl=12.1.109
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.1.105
  - cuda-runtime=11.8.0
  - cycler=0.11.0
  - daal4py=2023.1.1
  - dal=2023.1.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dpcpp-cpp-rt=2023.1.0
  - dpcpp_cpp_rt=2023.1.0
  - dpctl=0.14.2
  - emoji=2.2.0
  - entrypoints=0.4
  - executing=0.8.3
  - filelock=3.9.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.31
  - glog=0.5.0
  - icc_rt=2022.1.0
  - icu=68.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.12.0
  - intel-cmplr-lib-rt=2023.1.0
  - intel-cmplr-lic-rt=2023.1.0
  - intel-opencl-rt=2023.1.0
  - intel-openmp=2023.1.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.6
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=3.0.7
  - kiwisolver=1.4.4
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=11.1.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.2.106
  - libcurand-dev=10.3.2.106
  - libcurl=7.88.1
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libiconv=1.16
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.5.0
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lxml=4.9.2
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mistune=0.8.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpmath=1.2.1
  - munkres=1.1.4
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=1.1.1t
  - orc=1.7.4
  - packaging=23.0
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=2.5.2
  - plotly=5.14.1
  - pooch=1.7.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - protobuf=3.20.3
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pycparser=2.21
  - pydeck=0.8.0
  - pygments=2.15.1
  - pympler=1.0.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2023.3
  - pytz-deprecation-shim=0.1.0.post0
  - pywin32=305
  - pywinpty=2.0.10
  - pyyaml=6.0
  - pyzmq=25.0.2
  - qt=5.12.9
  - re2=2022.04.01
  - requests=2.29.0
  - rich=13.3.5
  - scikit-learn=1.2.2
  - scikit-learn-intelex=2023.1.1
  - scipy=1.10.1
  - send2trash=1.8.0
  - setuptools=66.0.0
  - six=1.16.0
  - smmap=3.0.5
  - snappy=1.1.9
  - sniffio=1.2.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - stanza=1.5.0
  - streamlit=1.22.0
  - sympy=1.11.1
  - tbb=2021.8.0
  - tenacity=8.2.2
  - terminado=0.17.1
  - threadpoolctl=3.1.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - tzlocal=4.3
  - urllib3=1.26.15
  - utf8proc=2.6.1
  - validators=0.20.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - watchdog=3.0.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=4.0.7
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - appdirs==1.4.4
      - kbbi==0.4.3
      - pyqt5-sip==4.19.18
      - pyqtchart==5.12
      - pyqtwebengine==5.12.1
      - torchaudio==2.0.2
      - torchvision==0.15.2
